### PR TITLE
Download files without compressing them

### PR DESCRIPTION
**Pull request by belkassaby**
*fix issue #28 : hp.json can be downloaded uncompressed with this commit

### CODE REVIEW

**Comment by pnrobinson** [comment]
I tried
 BioDownloaderBuilder builder = BioDownloader.builder(destination);
        builder.hpoJson()
                .hpDiseaseAnnotations();
        BioDownloader downloader = builder.build();
        List<File> files = downloader.download();

but got again a binary file for hp.json that was only 1.9 Mb

1.9M Mar  4 06:37 hp.json

**Comment by pnrobinson** [comment]
Another tries gave this download 
```
!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" >
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">
(...)
```

**Comment by pnrobinson** [comment]
I then tried to comment out the new line
/ //conn.setRequestProperty("Accept-Encoding", "");
and set the URLs to 
hp.json=https://github.com/obophenotype/human-phenotype-ontology/blob/master/hp.json
#http://purl.obolibrary.org/obo/hp.json
#hp.obo=http://purl.obolibrary.org/obo/hp.obo
hp.obo=https://github.com/obophenotype/human-phenotype-ontology/blob/master/hp.obo

but I still got
```
!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark" >
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://github.githubassets.com">
  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
  <link rel="preconnect" href="https://github.githubassets.com" crossorigin>
  <link rel="preconnect" href="https://avatars.githubusercontent.com">
(...)
```
strange. Should we try some pair./triple programming? It is not obvious to me what the problem is

**Comment by ielis** [comment]
I do not see any of the above mentioned issues. When adding the following test to ``, the code works fine, including downloading *uncompressed* `hp.json`.

```java
@Test
@Disabled("Requires internet access to run")
public void testHpoFileDownload() throws Exception {
    BioDownloader.builder(Path.of("target"))
            .hpoJson()
            .hpDiseaseAnnotations()
            .gencodeGrch38v39Basic()
            .build()
            .download();
}
```

**Review by ielis — APPROVED** [review]
Looks like this works!

**Comment by belkassaby** [comment]
The way I tested this was with the following code: 
```java  
@Test
public void testHpJsonFileDownload() throws Exception {
     BioDownloader bioDownloader = BioDownloaderBuilder.builder(resourcePath).hpJson().build();
     List<File> downloadedFile = bioDownloader.download();
}
```
And then checking the folder where the file had been created and opening it showed the readable json as opposed to previously downloading a zipped/binary file.

Let me know if that works for you Peter, so I can then merge to the dev branch.

**Comment by ielis** [comment]
@belkassaby , an issue with using `resourcePath` in the test above is that there already is a mock `hp.json` (four JSON lines) at `src/test/resources/hp.json`. So it sounds suspicious if the above works for you. It should not, as the download should be skipped.

**Comment by belkassaby** [comment]
My bad, I also added the .overwrite(true) so it would overwrite the existing file.

**Pull request merged**
