### PR TITLE
Modularize the library

### PR DESCRIPTION
**Pull request by ielis**
This PR addresses modularizing `biodownload` library ( #17 ).

### CODE REVIEW

**Comment by ielis** [comment]
@belkassaby I added the `module-info.java` file to the appropriate location of the library. The contents of the file should be fine, we are exporting the single package that we have in the library.

There is one thing that may be an issue - the `commons-net` library is neither modular, nor provides `Automatic-Module-Name` attribute in `MANIFEST.MF`.
This may be an issue in downstream applications, let's see..

**Comment by belkassaby** [comment]
Is there anything you think we should add to this PR before we merge?

**Comment by ielis** [comment]
It's unfortunate that `commons-net` is not modular, because it is a bad practice to create modular libraries (`biodownload`) that depend on non-modular libraries (`commons-net`). When you build the library on this branch, you will see the following in the compiler output:

```
[WARNING] ********************************************************************************************************************
[WARNING] * Required filename-based automodules detected. Please don't publish this project to a public artifact repository! *
[WARNING] ********************************************************************************************************************
```
However, uploading `biodownload` to Maven Central is *exactly* what we want to do. :confused: 

Do you think there is a workaround for downloading FTP files using pure Java (without using `commons-net`)?  If yes, then we can remove `commons-net` and solve this issue.

**Comment by belkassaby** [comment]
Let me have a quick look around if there is something more java vanilla to do so.

**Comment by belkassaby** [comment]
@ielis We could make it ourselves like here : https://examples.javacodegeeks.com/core-java/nio/java-nio-ftp-example/

**Comment by ielis** [comment]
That looks good. Do you think you could add the code to the repo? I think it would be OK to replace `commons-net` with the code, as we will be downloading from public FTPs practically all the time (no need for logins & passwords).

**Comment by belkassaby** [comment]
yes im currently testing it.

**Comment by belkassaby** [comment]
@ielis ok ,so here is the first commit: I created a new subpackage, created the NIOftp class used to download ftp files, and just removed the ftp method from `FileDownloader`. However if you prefer I can also put everything into the FileDownloader.
Added a few tests. Everything throws `FileDownloadExceptions` too.

**Comment by ielis** [comment]
The code looks good, we resolved the issue with the module path and we can download FTP files. 
I think this is OK for now. 

@belkassaby if things look good to you too, then please merge the PR.

**Comment by belkassaby** [comment]
Ok, let me change something before
(ftp should throw `FileDownloadException` instead of `IllegalArgumentException`)

**Comment by ielis** [comment]
Aw.. We should have merged this to `development`. I have set up the PR in a wrong way.

**Pull request merged**
